name: "Electron: Build & Push"
on:
  push:
    branches:
      - main
    paths:
      - 'electron/**'
      - '.github/workflows/electron.yml'
  pull_request:
    paths:
      - 'electron/**'
      - '.github/workflows/electron.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: electron
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/soloai/vscode-dev-containers-electron:${{github.event_name == 'pull_request' ? format('pr-{0}', github.event.issue.number) : 'latest'}}"
